version: '3'
services:

  JavaApp:
    image: openjdk:17
    ports:
      - 48888:8080
    tty: true
    volumes:
      - ./diary:/srv:cached
    working_dir: /srv

  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db-store/data:/var/lib/postgresql/data
      - ./db-store/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: sample-db

    